### ISSUE TITLE
Should CSS Custom Properties work with Sass variables?

### ISSUE THREAD

**Issue by mattdsteele** [sass/sass-spec#1263]
Given this SCSS:

```css
  $sassVar: red;
    foo {
        --var: $sassVar;
        background-color: var(--var, $sassVar);
    }
```

Both dart-sass and node-sass currently output:

```css
foo {
  --var: $sassVar;
  background-color: var(--var, red);
}
```

Previous versions of the compiler (for example, Ruby Sass v3.4.25) "honored" the Sass variable and produced:

```css
foo {
  --var: red;
  background-color: var(--var, red);
}
```

Is this valid SCSS? Or should I avoid initializing a custom property with a Sass variable?
