### ISSUE TITLE
Additional test case for `@extend`

### ISSUE THREAD

**Issue by connorskees** [sass/sass-spec#1678]
Hello,

I found an interesting bug in my implementation of `@extend` that I think would be useful to add here. I'll try to submit a pr for this case sometime this week.

```scss
c b {
  @extend %d;
}

c > b {
  @extend %d;
}

%d {
  color: red;
}
```
