### ISSUE TITLE
Missing error spec test for map to css output

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#858]
The following and probably related cases have AFAICS no spec test yet:

```scss
$map: ( foo: bar );
test { baz: $map; }
```
